### ISSUE TITLE
Support for encryption handler version 4

### ISSUE THREAD

**Issue by martin-bailey** [Yuras/pdf-toolbox#13]
I would like to use pdf-toolbox with files using the new encryption handler version 4. At the moment those files fail to open. Many other open source libraries fail as well but poppler works.

**Comment by Yuras** [comment]
OK, it appears to be harder then I expected. I'm working on it, but I will not be able to finish it during the weekend.

**Comment by Yuras** [comment]
@martin-bailey I implemented it in HEAD. But I'm currently in a process of API redesign, so it is not ready for release yet. So I ported it to the stable version, see "stable" branch. Please try it out. Let me know if you want me to release it on hackage right now.

I'm closing the issue, but please feel free to reopen if it still not working for you.
