### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriel439** [Yuras/pdf-toolbox#21]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that will break your package then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by Yuras** [comment]
Fixed in stable branch via 5d8c09da0f9ace24b532c19fadb0c557e96c5953
HEAD doesn't depend on `errors`.

Thank you for letting me know.

**Comment by Gabriel439** [comment]
You're welcome!

**Comment by Gabriel439** [comment]
Oh, also don't forget to upload this to Hackage when you get a chance.  There is no hurry, as I will still wait a few weeks before uploading `errors-2.0`.
