### ISSUE TITLE
Cannot compile examples

### ISSUE THREAD

**Issue by rolfschr** [Yuras/pdf-toolbox#22]
(Disclaimer: I'm a Haskell newbie)

I wanted to try out the examples. I did the follwoing

$ cabal --version
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
$ git clone https://github.com/Yuras/pdf-toolbox.git
$ cd pdf-toolbox/examples
$ make
ghc --make -outputdir=.build -Wall -i../core/lib -i../document/lib -i../content/lib -O -rtsopts  change-document-title.hs
...
                                                                                                                                 
change-document-title.hs:37:5:
    Not in scope: `runPdfWithHandle'
    Perhaps you meant `pdfWithHandle' (imported from Pdf.Toolbox.Document)

change-document-title.hs:46:17: Not in scope: `getRIS'

change-document-title.hs:46:28: Not in scope: `size'

change-document-title.hs:51:19: Not in scope: `setValueForKey'

change-document-title.hs:51:43:
    Not in scope: data constructor `OStr'

change-document-title.hs:51:50:
    Not in scope: data constructor `Str'

change-document-title.hs:52:17: Not in scope: `setValueForKey'

change-document-title.hs:52:40:
    Not in scope: data constructor `ONumber'
    Perhaps you meant `Number' (imported from Pdf.Toolbox.Document)

change-document-title.hs:52:50:
    Not in scope: data constructor `NumInt'

change-document-title.hs:54:14: Not in scope: `getRIS'

change-document-title.hs:55:7:
    Not in scope: `seek'
    Perhaps you meant `Streams.peek' (imported from System.IO.Streams)

change-document-title.hs:56:7: Not in scope: `inputStream'

change-document-title.hs:57:5:
    Not in scope: `liftIO'
    Perhaps you meant one of these:
      `liftM' (imported from Control.Monad),
      `liftM2' (imported from Control.Monad),
      `liftM3' (imported from Control.Monad)

change-document-title.hs:60:30:
    Not in scope: data constructor `ODict'
    Perhaps you meant `Dict' (imported from Pdf.Toolbox.Document)
make: *** [change-document-title] Error 1

Running /travis.sh before did not help either. (I was asked to update cabal but I cannot reproduce that output anymore).

**Comment by Yuras** [comment]
Examples are broken in master, I need to update them to new API. Try to checkout `stable` branch for now.

**Comment by rolfschr** [comment]
Ah, ok, thanks for the quick answer.

**Comment by Yuras** [comment]
Fixed via 12d2ea0f8c6fbb0c085b82e2d4ecf291a65b9016, ef0ef8d25dda3609362dbb19a70a8b980392eac1, 474680c79753984b04f7c157307d987b9be01c00 and 8e55976ef1ae91ba86f3f5f01501b1d445860e13
