### ISSUE TITLE
Please add support for recent versions of errors

### ISSUE THREAD

**Issue by peti** [Yuras/pdf-toolbox#23]
After updating NixOS to errors 2.x, we can no longer built your package: http://packdeps.haskellers.com/feed?needle=pdf-toolbox-core.

**Comment by Yuras** [comment]
Fixed via 4300a10ae910fc0b1d11a9bfff93bcecf0012f02
Thank you for reporting.

**Comment by peti** [comment]
Will you release a new version?

**Comment by Yuras** [comment]
It is already released on hackage
