### ISSUE TITLE
Support XObject forms in text extraction

### ISSUE THREAD

**Issue by Yuras** [Yuras/pdf-toolbox#27]
They can contain text.

See section `4.9 Form XObjects` in the PDF1.7 spec.

**Comment by Yuras** [comment]
Fixed in stable via ea60f3b1e4b975d2cfa431e52ca3a26043c3f79d

@MaxDaten, now we should successfully extract text from the file you sent me for #25.
Please report any further issue.

**Comment by MaxDaten** [comment]
Great! I owe you one! I will give it a try next week.
Yuras <notifications@github.com> schrieb am Fr., 16. Okt. 2015 um 14:25:

**Comment by Yuras** [comment]
Fixed in master via 60de9802c7b2f6c41f44948eaeaba945e93956c5
