### ISSUE TITLE
enable stackage for better dependency management

### ISSUE THREAD

**Issue by doofin** [Yuras/pdf-toolbox#38]

**Comment by Yuras** [comment]
It's a surprise for me that `pdf-toolbox` is not on stackage. It definitely [was](https://www.stackage.org/package/pdf-toolbox-document/snapshots), and I'm not sure what happened.

Right now `pdf-toolbox` is a state where the stable version is almost dead (but not yet) and the new one is almost done (but not yet). And I'm out of energy to finish it. In this situation I'm not going to invest time into investigating this issue with stackage. But it would be awesome if someone takes maintainance on stackage.

**Comment by doofin** [comment]
thanks! sorry for my oversight

**Comment by Yuras** [comment]
Seems to be on stackage already, see e.g. 88
