### ISSUE TITLE
Expose constructors?

### ISSUE THREAD

**Issue by o1lo01ol1o** [Yuras/pdf-toolbox#53]
Hi,
  I have a use case where I need to build up an ADT representation of a (smallish) pdf document in order to do some analysis on it.  I notice that the `Page` constructor is not exported.  Could it (and any other ctors needed to represent the full document) be exported so that users can de-structure nodes?  
Thanks

**Comment by Yuras** [comment]
@o1lo01ol1o Hi, are you using the `master` or the version from Hackage? The former exposes `Page` constructor from `Pdf.Document.Internal.Types`, the later - from `Pdf.Toolbox.Document.Internal.Types`.

Though I don't think it will help you, `Page` contains a reference into the corresponding object in the PDF file, so it's not a persistent data structure.

**Comment by o1lo01ol1o** [comment]
> The former exposes Page constructor from Pdf.Document.Internal.Types

Ah, I missed this, thanks!

> Though I don't think it will help you, Page contains a reference into the corresponding object in the PDF file, so it's not a persistent data structure.

Yes, I'm aware that I'll need to build something by following those references.
