### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by lueck** [Yuras/pdf-toolbox#55]
Hi,

glyphs encoded in fixed with multi-byte encodings like UCS-2 or UTF16BE are not decoded correctly.

This is caused by `unicodeCMapNextGlyph` in `UnicodeCMap.hs`. It eats 1 byte (then 2, then 3, then 4 bytes) of a byte string, and tests each time, if these bytes are in a character range given in den CMap. If not, a further byte (up to 4 bytes) is eaten and tested again. If the test is passed, the glyph code and the rest of the byte string is returned. But this fails for 2-byte encodings like UCS-2: Here, the character range is 0x0000-0xFFFF. E.g. the long s is represented by the ByteString `"\x01x7f"`. When this is read by `unicodeCMapNextGlyph`, it first reads `"\x01"`, and the range test is passed, because `"\x00\x00"<="\x01"<="\xFF\xFF"`. So the character encoded in two bytes is decoded into two characters instead of one.

If there is something like

    1 begincodespacerange
    <0000> <FFFF>
    endcodespacerange

in the CMap, we always have to read 2 bytes, but never only a single one. See Adobe's tutorial about [CMap Resources](https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5099.CMapResources.pdf).

The same issue can be observed for UTF16 and UTF32 encodings.

I've written a fix and will send a pull request soon.

The issue can be seen in the output, e.g. of `textract`. Here is an example, with the long letter S, U+x017f: It is taken from [Google Books](https://books.google.de/books?id=LMxqbUvq7O0C&pg=PR18), which uses UCS-2 encoding. It's from page 23 of the downloadable PDF, second line. The long S is the first letter of "ſeines". The glyph data is extracted using textract, where the page number has been set to 23.

    ...
    [Glyph {glyphCode = 115, glyphTopLeft = Vector 198.40982494150288 394.2519882494149, glyphBottomRight = Vector 198.30982494175288 404.2519882244149, glyphText = Just "s"}]
    [Glyph {glyphCode = 1, glyphTopLeft = Vector 150.009 393.968, glyphBottomRight = Vector 149.90900000025 403.967999975, glyphText = Nothing},Glyph {glyphCode = 127, glyphTopLeft = Vector 150.009 393.968, glyphBottomRight = Vector 149.90900000025 403.967999975, glyphText = Nothing}]
    [Glyph {glyphCode = 101, glyphTopLeft = Vector 153.4488299914004 394.00239829991403, glyphBottomRight = Vector 153.3488299916504 404.002398274914, glyphText = Just "e"}]
    ...

See the `Nothing` in the `glyphText`, but the 1 and 127 in the `glyphCode`, which is the bytestring "\x01\x7f" broken into two glyphs.

Kind regards,
Christian

**Comment by Yuras** [comment]
Hi @lueck, thank you for the detailed report. I'll take close look later, but please feel free to make a PR.
BTW does it occur in `master` or in the version from hackage?

**Comment by lueck** [comment]
Hi @Yuras, it's occurs on master.

**Comment by Yuras** [comment]
We decided to go with #57
