### ISSUE TITLE
Parse font descriptor

### ISSUE THREAD

**Issue by Yuras** [Yuras/pdf-toolbox#6]
In particular we need `FontBBox` -- font bounding box. Useful to guess spaces/newlines in glyph stream.

**Comment by vandenoever** [comment]
Is it possible to get the names of all the used fonts already or is that part of this enhancement request?

**Comment by Yuras** [comment]
@vandenoever You can try [pageFontDicts](http://hackage.haskell.org/package/pdf-toolbox-document-0.0.7.1/docs/Pdf-Toolbox-Document-Page.html#v:pageFontDicts). Though IIRC it returns font name as used inside the content stream (something like an alias), so you may need to use lower-level API from `pdf-toolbox-core` to get more info.

**Comment by vandenoever** [comment]
The names that pageFontDicts give back are e.g. 'Name "F1"', 'Name "F2"' etc.

Grepping for 'font' in core gives no hits, so I guess more PDF knowledge is needed to get information from there.

**Comment by Yuras** [comment]
Yes, `core` package provides raw access to PDF internals, including font dictionaries and font descriptors. You have to know where to look for font names to use it. Chapter 5 of pdf reference (v1.7) describes everything about text and fonts. But after quick skimming over the docs, I'm even not even sure what "font name" means exactly. It could be a `BaseFont` field in font dictionary, or `FontName` in font descriptor dictionary. Both are described as "The PostScript name of the font."

**Comment by vandenoever** [comment]
The tool `pdffonts` gives reasonable output:
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
ABCDEE+Calibri                       TrueType          WinAnsi          yes yes no       5  0
ABCDEE+Calibri,Italic                TrueType          WinAnsi          yes yes no       9  0
ABCDEE+Calibri,Bold                  TrueType          WinAnsi          yes yes no      11  0
Symbol                               CID TrueType      Identity-H       yes no  yes     13  0
Arial                                TrueType          WinAnsi          no  no  no      18  0
ABCDEE+Cambria                       TrueType          WinAnsi          yes yes no      20  0
ABCDEE+Courier New                   TrueType          WinAnsi          yes yes no      22  0
ABCDEE+Wingdings                     CID TrueType      Identity-H       yes yes yes     24  0
ABCDEE+Cambria                       CID TrueType      Identity-H       yes yes yes     33  0
```
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
BAAAAA+DejaVuSans                    TrueType          WinAnsi          yes yes yes     24  0
CAAAAA+DejaVuSans-Bold               TrueType          WinAnsi          yes yes yes     19  0
DAAAAA+OpenSymbol                    TrueType          WinAnsi          yes yes yes     29  0
EAAAAA+DejaVuSansMono                TrueType          WinAnsi          yes yes yes     34  0
```

**Comment by vandenoever** [comment]
`pdffonts` appears to be using BaseFont:
```bash
$ pdffonts 2516.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
DejaVuSans                           CID TrueType      Identity-H       yes no  yes      7  0
DejaVuSans-Bold                      CID TrueType      Identity-H       yes no  yes      8  0
DejaVuSansMono                       CID TrueType      Identity-H       yes no  yes      9  0

[nix-shell:~/akademy2016/rust]$ strings 2516.pdf |grep BaseFont|sort -u
/BaseFont /DejaVuSans
/BaseFont /DejaVuSans-Bold
/BaseFont /DejaVuSansMono

[nix-shell:~/akademy2016/rust]$ strings 2516.pdf |grep FontName|sort -u
/FontName /QCBAAA+DejaVuSans
/FontName /QHBAAA+DejaVuSans-Bold
/FontName /QXAAAA+DejaVuSansMono
```

**Comment by Yuras** [comment]
@vandenoever sorry for the delay.

I added a `fontName` function, see 1dc40eb9646ec261ab2fd88f4fd6efbc9329c9ee (`stable` branch). Please try it out.

**Comment by vandenoever** [comment]
Great! What would be a good way to test it? create a small project with cabal that somehow points to 1dc40eb as dependency?

**Comment by Yuras** [comment]
Sorry again, I'm a bit busy these days...

If you are using `cabal`, then you can checkout the package locally and then `add-source` it into a sandbox. If you are using `stack`, then you can use `location` in `stack.yaml` to point to the commit, see https://docs.haskellstack.org/en/stable/yaml_configuration/?highlight=location#complex-package-locations-location
