### ISSUE TITLE
Nix isolated tests fail due to a missing file

### ISSUE THREAD

**Issue by coderfromhere** [Yuras/pdf-toolbox#71]
Hi! I've been testing the [recent release](https://github.com/Yuras/pdf-toolbox/issues/42) with Nix lately, and here's the test suite error that I get:

```
Preprocessing test suite 'test' for pdf-toolbox-document-0.1.1..
Building test suite 'test' for pdf-toolbox-document-0.1.1..
[1 of 2] Compiling Test.Internal.Util ( test/Test/Internal/Util.hs, dist/build/test/test-tmp/Test/Internal/Util.o )
[2 of 2] Compiling Main             ( test/test.hs, dist/build/test/test-tmp/Main.o )
Linking dist/build/test/test ...
running tests
Running 1 test suites...
Test suite test: RUNNING...

Internal.Util
  decodeTextString
    when string starts with BOM
      decodes it as UTF16BE
    when string doesn't start with BOM
      decodes it as PDFDocEncoding string
simple.pdf
  should have title
nested_xobject
  should have correct text FAILED [1]

Failures:

  test/test.hs:42:5: 
  1) nested_xobject should have correct text
       uncaught exception: IOException of type NoSuchThing
       test/files/nested_xobject.pdf: openBinaryFile: does not exist (No such file or directory)

  To rerun use: --match "/nested_xobject/should have correct text/"
```

I understand that the current setup may not necessarily optimise for fully-isolated Nix builds, so this issue is just a FYI input about possible issues out there. And regular cabal builds work just fine. The only side-effect of that issue is that a corresponding Nix derivation of the package will be marked as `broken` and users [will have to explicitly unbreak it](https://discourse.nixos.org/t/video-tutorial-how-to-fix-broken-haskell-packages-in-nix/3968) with [available API](https://github.com/bgamari/nixpkgs/commit/cdf1a522cacfb209e340af9d51c2ac4dd84e7124)

**Comment by Yuras** [comment]
Thanks! I believe #72 should fix it.

**Comment by coderfromhere** [comment]
yeah, that must be it, thanks!

**Comment by Yuras** [comment]
Released https://hackage.haskell.org/package/pdf-toolbox-document-0.1.2
