### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by hsenag** [Yuras/pdf-toolbox#86]
It'd be great if you could make a Hackage release (including #85) - I'm currently having to point to the git repository in `cabal.project` :-)

**Comment by Yuras** [comment]
I released all three packages. Though I don't see what's wrong with using git repo in project file :)

**Comment by hsenag** [comment]
Thanks! It's not too bad when it's something like this that's near the top of the library stack but it does make some things more awkward.
